FROM alpine:3.11
RUN  apk update && apk add --no-cache tzdata \ 
   && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
   && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /usr/src/bloom
COPY --from=valeriansaliou/bloom:v1.28.0 /usr/local/bin/bloom /usr/local/bin/bloom
CMD [ "bloom", "-c", "/etc/bloom.cfg" ]
EXPOSE 8080 8811